#!/bin/sh 

[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-pppoeserver ) && rm -f /etc/uci-defaults/luci-pppoeserver
	chmod 755 /etc/init.d/pppoeserver  >/dev/null 2>&1
	/etc/init.d/pppoeserver enable  >/dev/null 2>&1	
	exit 0
}

