#!/bin/sh 

uci -q batch <<-EOF >/dev/null
          delete ucitrack.@mldonkey[-1]
          add ucitrack mldonkey
          set ucitrack.@mldonkey[-1].init=mldonkey
          commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
