#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-mldonkey ) && rm -f /etc/uci-defaults/luci-mldonkey
	chmod 755 /etc/init.d/mldonkey >/dev/null 2>&1
   /etc/init.d/mldonkey enable >/dev/null 2>&1
	exit 0
}
